### ISSUE TITLE
Wrong GST details in item table

### ISSUE THREAD

**Issue by rtdany10** [resilient-tech/india-compliance#1705]
### Information about bug

![image](https://github.com/resilient-tech/india-compliance/assets/52111700/afd1a615-8650-47df-869a-17125cf673b3)

As seen in the image above, CGST Amount is wrong in the second row.
Taxable value is 1890, but CGST Amount(9%) is shows as 245, which is same for the 3rd row.

Seems to happen when same item is added more than twice?

### Version

ERPNext: v15.14.3 (HEAD)
Frappe Framework: v15.14.1 (HEAD)
India Compliance: v15.5.1 (HEAD)

### Relevant log output / Stack trace / Full Error Message.

*No response*

### Code of Conduct

* [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Looks like this was fixed and released in 15.3.0
https://github.com/resilient-tech/india-compliance/commit/fa1c0ead422668926ed3d0008b371c2c6960fee1#diff-daf9ff43d80eee4a7b5733e3aee0137865b04f4c6296d765a0e7a2537f165aed

We however did not patch this, as we were not using it for GST reports or e-Invoice at the moment.

Is it possible this was an old invoice from the previous version? Can you replicate this issue in v15.5.1?

**Comment by rtdany10** [comment]
@vorasmit Invoice was created today on version India Compliance: v15.5.1 (HEAD)

**Comment by rtdany10** [comment]
![image](https://github.com/user-attachments/assets/9fa00345-4bd7-48f2-80b5-135a4df3f46a)

Still happens :(

**Comment by rtdany10** [comment]
@vorasmit @ljain112 

![image](https://github.com/user-attachments/assets/291cee16-2a98-4dd5-ad81-3758c087dbc6)


still happens :(

**Comment by vorasmit** [comment]
Item wise tax detail is calculated in ERPNext. However, I just checked this in v15 and develop and works as expected.

I assume its the issue is: 
=> Same Item => Different Item Rate => Tax rate as zero in Item Wise Tax Detail.

If it's something else, can you please share the steps to replicate the issue?

**Comment by vorasmit** [comment]
Looks like this is different from the original issue.

**Comment by rtdany10** [comment]
> Item wise tax detail is calculated in ERPNext.

Sorry, I'll report on ERPNext repo :grimacing: 
But because of this issue, GST Itemised Sales Register shows wrong data.

<hr>

Seems to work fine on v15 when I tested as well.
v14 has the issue. 

Steps to replicate on v14:
1. Create an invoice with the same item repeating twice(2 different rows).
2. In the first row, set the rate as zero
3. In the second row, set a value as rate
4. Check the report
